### ISSUE TITLE
"Mongo server seems to really be down." error

### ISSUE THREAD

**Issue by suriyaa** [josephwegner/simple-example#1]
Hello @josephwegner, :smile: 

> I got an `Mongo server seems to really be down.  We tried 5 times.  Tough luck.` console error.

What should I do?

_Yours,_
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

**Comment by josephwegner** [comment]
Hey Suriyaa,

To be completely honest, I would not suggest using Simple-API at all. This
library has been out of maintenance for years, and I would not suggest
anyone use it in production at this point. That said, I'm going to consider
the library deprecated, and not provide much support.

I would suggest using a more mature library like Express.

**Comment by suriyaa** [comment]
@josephwegner ok. :+1:
